### ISSUE TITLE
Upload-Error

### ISSUE THREAD

**Issue by xNiika** [Xenthys/ShareXen#24]
Hey,

I've transfered my ShareXen configuration 1:1 to a new server on the same domain.

Now I'm getting the following error when trying to upload an image:
```
The API was unable to save your file, please tell an administrator.

Status code:
(500) Internal Server Error

Response text:
{"api_version":"2.4.1","api_source":"https:\/\/github.com\/Xenthys\/ShareXen","endpoint":"upload","username":"kjell","iteration_count":1,"error":"upload_failed","error_msg":"The API was unable to save your file, please tell an administrator.","http_code":500,"status":"error","execution_time":0.0010449886322021484}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
```
What could cause this issue?

**Comment by Xenthys** [comment]
Hi, it's a permission issue, the user that runs PHP (or Apache2 if you use mod_php) doesn't have the permissions to write in the script's directory. It is recommended to `chown -R www-data:www-data /var/www` if you use a standard configuration.

**Comment by xNiika** [comment]
Thanks for the quick help!
